# ~/.tmux.conf

set-environment -g TMUX_PLUGIN_MANAGER_PATH ~/.config/tmux/plugins

# Options to make tmux more pleasant
set -g mouse on
set -g default-terminal "tmux-256color"

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'pwittchen/tmux-plugin-ip'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

# custom catpuccin modules
%hidden MODULE_NAME="player"
set -g "@catppuccin_${MODULE_NAME}_icon" " 🎵 "
#set -gF "@catppuccin_${MODULE_NAME}_color" "#{E:@thm_teal}"
set -g "@catppuccin_${MODULE_NAME}_text" "#[fg=white]#(playerctl metadata --format '{{artist}} - {{title}}') "
set -g status-right "#{E:@catppuccin_status_player}"

#%hidden MODULE_NAME_2="distro"
#set -g "@catppuccin_${MODULE_NAME_2}_icon" " "
#set -gF "@catppuccin_${MODULE_NAME_2}_color" "#{E:@thm_teal}"
#set -g "@catppuccin_${MODULE_NAME_2}_text" "#[fg=white]#(awk -F= '/^NAME=/ {gsub(/\"/,\"\",\$2); print \$2}' /etc/os-release)"
#set -g status-right "#{E:@catppuccin_status_distro}"
#
#source ".config/tmux/plugins/catppuccin/tmux/utils/status_module.conf"

# set window split
bind-key | split-window -h
bind-key - split-window

# better key-binding
set-option -g prefix C-a
bind-key C-a last-window
bind-key a send-prefix
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_player}"
#set -ag status-right "#{E:@catppuccin_status_distro}"
#set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
#set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"
#set -agF status-right "#[fg=#{@thm_crust},bg=#{@thm_teal}] ##H "


# set -g status-left '#[fg=green]#(whoami) #[fg=red]• #[fg=green,bright]#(awk -F= "/^NAME=/ {gsub(/\"/,\"\",\$2); print \$2}" /etc/os-release)#[default] #[fg=red]• #[fg=white,dim]#(hostname)'

# Faster key repetition
set -s escape-time 0
# Start numbering at 1
set -g base-index 1

setw -g aggressive-resize on

# init tmux plugin manager
run -b ~/.config/tmux/plugins/tpm/tpm
